process.env.TWITTER_CONSUMER_KEY = 'vKFUlP3Dk65fDFelOn26rtFAK';
process.env.TWITTER_CONSUMER_SECRET = 'MvEKXwGFksrAYujGkYy592PASMYZWjUHKAjODHdeXltWic1u2T';
process.env.TWITTER_ACCESS_TOKEN_KEY = '4533837511-Q6xZXRQHvZh0OBA98iJbVMDvCIROqCrMowt4Yon';
process.env.TWITTER_ACCESS_TOKEN_SECRET = '8sxxJEZ9cDijqUrR10ovPojTwJ4awi84oVJVMqX8UOfbN';
